name: Test workflow

on: [pull_request]

jobs:
  test-action:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/github-script@v3
        with:
          script: |
            console.log('hello world')
